### ISSUE TITLE
Possible dictionary improvement

### ISSUE THREAD

**Issue by ghost** [Lyroxide/yomichan-ko-dic#1]
I found a github repository that used a different approach towards making yomichan dictionary, this repository used an edited version of yomichan and achieved better results than yours, the problem though is that this repository is supporting only 4 languages now (Fr, Ru, Es, Ge) and i'm not a developer, maybe you should give it a look. (I've tested the Spanish dictionary and it handled the verbalizations perfectly)

https://github.com/seth-js/yomichan-es

The data used for the dictionary was collected from this website (https://kaikki.org/dictionary/Korean/index.html)

**Comment by Lyroxide** [comment]
I am aware of his repos. However, doing the same method for Korean is not a great idea.

I am currently working on a Yomichan-esque deconjugator for Korean, no promises tho

**Comment by ghost** [comment]
Thanks for your response, i hope the dictionary you're working on goes well, and hopefully all of us can find it useful in the future.
